package com.mx.ukisi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Metrica implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Metrica() {
    }

}