package com.mx.ukisi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Metrica implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("nombre")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label("valor")
   private java.lang.Integer valor;

   @org.kie.api.definition.type.Label(value = "crea incidencia")
   private boolean levantaInicidencia;

   public Metrica()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Integer getValor()
   {
      return this.valor;
   }

   public void setValor(java.lang.Integer valor)
   {
      this.valor = valor;
   }

   public boolean isLevantaInicidencia()
   {
      return this.levantaInicidencia;
   }

   public void setLevantaInicidencia(boolean levantaInicidencia)
   {
      this.levantaInicidencia = levantaInicidencia;
   }

   public Metrica(java.lang.String nombre, java.lang.Integer valor,
         boolean levantaInicidencia)
   {
      this.nombre = nombre;
      this.valor = valor;
      this.levantaInicidencia = levantaInicidencia;
   }

}