package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Jerarquia implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String type;
   private java.util.List<com.ikusi.brms.beans.Device> nodos;

   public Jerarquia()
   {
       nodos= new  java.util.ArrayList<>();
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.util.List<com.ikusi.brms.beans.Device> getNodos()
   {
      return this.nodos;
   }

   public void setNodos(java.util.List<com.ikusi.brms.beans.Device> nodos)
   {
      this.nodos = nodos;
   }

   public Jerarquia(java.lang.String id, java.lang.String type,
         java.util.List<com.ikusi.brms.beans.Device> nodos)
   {
      this.id = id;
      this.type = type;
      this.nodos = nodos;
   }

}