package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@XStreamAlias("metrics")
public class Metrics implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "metrics")
   @XStreamImplicit(itemFieldName = "metric")
   private java.util.List<com.ikusi.brms.beans.Metric> metrics;

   public Metrics()
   {
   }

   public java.util.List<com.ikusi.brms.beans.Metric> getMetrics()
   {
      return this.metrics;
   }

   public void setMetrics(java.util.List<com.ikusi.brms.beans.Metric> metrics)
   {
      this.metrics = metrics;
   }

   public Metrics(java.util.List<com.ikusi.brms.beans.Metric> metrics)
   {
      this.metrics = metrics;
   }

}