package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Nodo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Nodo() {
    }

}