package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

@com.thoughtworks.xstream.annotations.XStreamAlias("parents")
public class Parents implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("parents")
   @com.thoughtworks.xstream.annotations.XStreamImplicit(itemFieldName = "parent")
   private java.util.List<com.ikusi.brms.beans.Parent> parents;

   private java.util.List<java.lang.String> parentsAsString;

   public Parents()
   {
   }

   public java.util.List<com.ikusi.brms.beans.Parent> getParents()
   {
      return this.parents;
   }

   public void setParents(java.util.List<com.ikusi.brms.beans.Parent> parents)
   {
      this.parents = parents;
   }

   public java.util.List<java.lang.String> getParentsAsString()
   {
      java.util.List<java.lang.String> list= new java.util.ArrayList<>();
       
      for(com.ikusi.brms.beans.Parent parent: parents){
          list.add(parent.get);
      }
       
      return this.parentsAsString;
   }

   public void setParentsAsString(java.util.List<java.lang.String> parentsAsString)
   {
      this.parentsAsString = parentsAsString;
   }

   public Parents(java.util.List<com.ikusi.brms.beans.Parent> parents,
         java.util.List<java.lang.String> parentsAsString)
   {
      this.parents = parents;
      this.parentsAsString = parentsAsString;
   }

}