package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

@com.thoughtworks.xstream.annotations.XStreamAlias("parents")
public class Parents implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("parents")
   @com.thoughtworks.xstream.annotations.XStreamImplicit(itemFieldName = "parent")
   private java.util.List<java.lang.String> parents;

   public Parents()
   {
      
   }

   public java.util.List<java.lang.String> getParents()
   {
      return this.parents;
   }

   public void setParents(java.util.List<java.lang.String> parents)
   {
      this.parents = parents;
   }

   

   public Parents(java.util.List<java.lang.String> parents)
   {
      this.parents = parents;
   }

}