package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Parent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Parent()
   {
   }

}