package com.ikusi.brms.beans;

import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import javax.xml.bind.annotation.XmlRootElement;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import com.thoughtworks.xstream.converters.collections.CollectionConverter;

/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.xml.bind.annotation.XmlRootElement(name = "request")
public class Request implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("event")
   @com.thoughtworks.xstream.annotations.XStreamAlias("event")
   private com.ikusi.brms.beans.Event event;
   @org.kie.api.definition.type.Label("device")
   @com.thoughtworks.xstream.annotations.XStreamAlias("device")
   private com.ikusi.brms.beans.Device device;
   @org.kie.api.definition.type.Label("metrics")
   @com.thoughtworks.xstream.annotations.XStreamAlias("metrics")
   private com.ikusi.brms.beans.Metrics metrics;
   @org.kie.api.definition.type.Label("parents")
   @com.thoughtworks.xstream.annotations.XStreamAlias("parents")
   private com.ikusi.brms.beans.Parents parents;

   @org.kie.api.definition.type.Label("response")
   @com.thoughtworks.xstream.annotations.XStreamAlias("response")
   private com.ikusi.brms.beans.Response response;

   @org.kie.api.definition.type.Label("inMemory")
   private java.lang.Boolean inMemory;

   @org.kie.api.definition.type.Label("statusBRMS")
   private java.lang.String statusBRMS;

   private String jerarquia;

   public Request()
   {
   }

   public com.ikusi.brms.beans.Event getEvent()
   {
      return this.event;
   }

   public void setEvent(com.ikusi.brms.beans.Event event)
   {
      this.event = event;
   }

   public com.ikusi.brms.beans.Device getDevice()
   {
      return this.device;
   }

   public void setDevice(com.ikusi.brms.beans.Device device)
   {
      this.device = device;
   }

   public com.ikusi.brms.beans.Metrics getMetrics()
   {
      return this.metrics;
   }

   public void setMetrics(com.ikusi.brms.beans.Metrics metrics)
   {
      this.metrics = metrics;
   }

   public com.ikusi.brms.beans.Parents getParents()
   {
      return this.parents;
   }

   public void setParents(com.ikusi.brms.beans.Parents parents)
   {
      this.parents = parents;
   }

   public com.ikusi.brms.beans.Response getResponse()
   {
      return this.response;
   }

   public void setResponse(com.ikusi.brms.beans.Response response)
   {
      this.response = response;
   }

   public java.lang.Boolean getInMemory()
   {
      return this.inMemory;
   }

   public void setInMemory(java.lang.Boolean inMemory)
   {
      this.inMemory = inMemory;
   }

   public java.lang.String getStatusBRMS()
   {
      return this.statusBRMS;
   }

   public void setStatusBRMS(java.lang.String statusBRMS)
   {
      this.statusBRMS = statusBRMS;
   }

   public java.lang.String getJerarquia()
   {
      return this.jerarquia;
   }

   public void setJerarquia(java.lang.String jerarquia)
   {
      this.jerarquia = jerarquia;
   }

   public Request(com.ikusi.brms.beans.Event event,
         com.ikusi.brms.beans.Device device,
         com.ikusi.brms.beans.Metrics metrics,
         com.ikusi.brms.beans.Parents parents,
         com.ikusi.brms.beans.Response response, java.lang.Boolean inMemory,
         java.lang.String statusBRMS, java.lang.String jerarquia)
   {
      this.event = event;
      this.device = device;
      this.metrics = metrics;
      this.parents = parents;
      this.response = response;
      this.inMemory = inMemory;
      this.statusBRMS = statusBRMS;
      this.jerarquia = jerarquia;
   }

}