package com.ikusi.brms.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("resultado")
   private java.lang.String resultado;

   private java.lang.Integer tiempoEspera;

   public Response()
   {
   }

   public java.lang.String getResultado()
   {
      return this.resultado;
   }

   public void setResultado(java.lang.String resultado)
   {
      this.resultado = resultado;
   }

   public java.lang.Integer getTiempoEspera()
   {
      return this.tiempoEspera;
   }

   public void setTiempoEspera(java.lang.Integer tiempoEspera)
   {
      this.tiempoEspera = tiempoEspera;
   }

   public Response(java.lang.String resultado, java.lang.Integer tiempoEspera)
   {
      this.resultado = resultado;
      this.tiempoEspera = tiempoEspera;
   }

}