package example.testikusi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjIn implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ParametroUno")
   private java.lang.String parametroUno;
   @org.kie.api.definition.type.Label(value = "Parametro Dos")
   private java.lang.Integer parametroDos;

   public ObjIn()
   {
   }

   public java.lang.String getParametroUno()
   {
      return this.parametroUno;
   }

   public void setParametroUno(java.lang.String parametroUno)
   {
      this.parametroUno = parametroUno;
   }

   public java.lang.Integer getParametroDos()
   {
      return this.parametroDos;
   }

   public void setParametroDos(java.lang.Integer parametroDos)
   {
      this.parametroDos = parametroDos;
   }

   public ObjIn(java.lang.String parametroUno, java.lang.Integer parametroDos)
   {
      this.parametroUno = parametroUno;
      this.parametroDos = parametroDos;
   }

}