package example.gamesa;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BeanTest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BeanTest() {
        System.out.println("from bean test");
        
    }
    
    

     


}