package example.gamesa;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dispositivo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nombre dispotivo")
   private java.lang.String nombre;
   @org.kie.api.definition.type.Label(value = "IP")
   private java.lang.String ip;
   @org.kie.api.definition.type.Label(value = "Es padre")
   private java.lang.Boolean padre;
   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.String id;

   public Dispositivo()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getIp()
   {
      return this.ip;
   }

   public void setIp(java.lang.String ip)
   {
      this.ip = ip;
   }

   public java.lang.Boolean getPadre()
   {
      return this.padre;
   }

   public void setPadre(java.lang.Boolean padre)
   {
      this.padre = padre;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public Dispositivo(java.lang.String nombre, java.lang.String ip,
         java.lang.Boolean padre, java.lang.String id)
   {
      this.nombre = nombre;
      this.ip = ip;
      this.padre = padre;
      this.id = id;
   }

}