package example.gamesa;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dispositivo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Dispositivo() {
    }

}