package example.gamesa;

import java.util.Collection;

function void yourFunction(Collection colecion) {
	System.out.println("con funcion"+colecion);
	
	for(Object obj:colecion){
	    Dispositivo dis=(Dispositivo)obj;
	    System.out.println("from for: "+dis.getId());
	}
	
	
}

rule "gamesaConTiempo"
	
	when
		Dispositivo( padre : padre == false )
		
	then
	    BeanTest $bean= new BeanTest();
	    $bean.metodo();
		System.out.println("si evalua 4.2:");
		Collection list = kcontext.getKieRuntime().getObjects();
		yourFunction(list);
		
end