package com.ikusi.brms.beans;

import java.util.*;

function boolean hasParents(List lista){
    System.out.println("from function "+lista);
    return true;
}


rule "test envio request"
    no-loop true
when 
    request : Request( getEvent().getName()== "Test_0_3_XXX" )
then
    System.out.println("regla evaluada ver 1.0:"+request.getEvent().getName());
    request.getResponse().setResultado("CREATE");
    request.getResponse().setTiempoEspera(2);

    update( request );
    
end 


rule "device en memoria" 
   no-loop true
  
when
    request : Request( getStatusBRMS() == "INICIAL", $sysID:device.sysId, $event :event.name)
    Request($sysID != null,$event != null,inMemory == true, device.sysId == $sysID,event.name == $event );
then 
    System.out.println("the device: "+request.getDevice().getSysId() +" is already in memory whit the same event... ");
    System.out.println("whit event: "+request.getEvent().getName());
    System.out.println("return to FUSE: NO");
    retract(request);
end


rule "device en memoria diferente evento" 
   no-loop true
  
when
    request : Request( getStatusBRMS() == "INICIAL", $sysID:device.sysId, $event :event.name)
    Request($sysID != null,$event != null,inMemory == true, device.sysId == $sysID,event.name != $event );
then 
    System.out.println("the device: "+request.getDevice().getSysId() +" is already in memory whit the diferente event... ");
    System.out.println("whit event: "+request.getEvent().getName());
    System.out.println("whit event 2: "+$event);
    System.out.println("return to FUSE: ????");
    
end


rule "device no en memoria" 
   no-loop true
when
    request : Request( getStatusBRMS() == "INICIAL",inMemory == false,$sysID:device.sysId )
   not ( exists(  Request($sysID != null,inMemory == true, device.sysId == $sysID)));
then
    System.out.println("the device was insert in memory:"+request.getDevice().getSysId());
    System.out.println("return to FUSE: WAIT");
    request.setInMemory(true);
    request.setStatusBRMS("RESGISTRED");
    update(request);
end

rule "SAI gamesa"
   no-loop true
when
     request1 : Request(device.name == "SAI", statusBRMS == "INICIAL", event.name == "NODE DOWN", $sysID:device.sysId)
     request2 : Request($sysID != null,statusBRMS == "RESGISTRED",event.name== "POWER FAIL",device.sysId == $sysID);
then
    System.out.println("SAI down con previo power fail:");
    request2.setStatusBRMS("RESGISTRED");
    System.out.println("return to FUSE: WAIT for childrens");
    retract(request2);
end


rule "busca papa"
 no-loop true
when 
    request : Request(getStatusBRMS() == "RESGISTRED", parents.parents.size > 0, $padres:parents.parents ,hasParents($padres))

then 
System.out.println("ADSdsdasdasdasd version 1.1");
end 

