package com.ikusi.brms.beans;

import java.util.*;



rule "test envio request"
    no-loop true
when 
    request : Request( getEvent().getName()== "Test_0_3_XXX" )
then
    System.out.println("regla evaluada ver 1.0:"+request.getEvent().getName());
    request.getResponse().setResultado("CREATE");
    request.getResponse().setTiempoEspera(2);

    update( request );
    
end 


rule "device en memoria" 
   no-loop true
  
when
    request : Request( getStatusBRMS() == "INICIAL", $sysID:device.sysId, $event :event.name)
    Request($sysID != null,$event != null,inMemory == true, device.sysId == $sysID,event.name == $event );
then 
    System.out.println("the device: "+request.getDevice().getSysId() +" is already in memory whit the same event... ");
    System.out.println("whit event: "+request.getEvent().getName());
    System.out.println("return to FUSE: NO");
    retract(request);
end


rule "device en memoria diferente evento" 
   no-loop true
  
when
    request : Request( getStatusBRMS() == "INICIAL", $sysID:device.sysId, $event :event.name)
    Request($sysID != null,$event != null,inMemory == true, device.sysId == $sysID,event.name != $event );
then 
    System.out.println("the device: "+request.getDevice().getSysId() +" is already in memory whit the diferente event... ");
    System.out.println("whit event: "+request.getEvent().getName());
    System.out.println("whit event 2: "+$event);
    System.out.println("return to FUSE: ????");
    
end


rule "device no en memoria" 
   no-loop true
when
    request : Request( getStatusBRMS() == "INICIAL",inMemory == false,$sysID:device.sysId )
   not ( exists(  Request($sysID != null,inMemory == true, device.sysId == $sysID)));
then
    System.out.println("the device was insert in memory:"+request.getDevice().getSysId());
    System.out.println("return to FUSE: WAIT");
    request.setInMemory(true);
    request.setStatusBRMS("SAVED");
    update(request);
end


rule "add to jerarquia as child"

when 
    child: Request( getStatusBRMS()== "SAVED", getJerarquia() == null,parents.parents != null ,parents.parents.size > 0, $padres:parents.parents )
    parent : Request(getJerarquia() != null, new Parent(device.sysId ) memberOf  $padres, $idPadre:device.sysId );
then    
    System.out.println("add child"+child.getDevice().getSysId());
    System.out.println("to hierarchy"+parent.getJerarquia().getId());
    child.setJerarquia(parent.getJerarquia());
    parent.getJerarquia().getNodos().add(child);
    
    update(parent);
    update(child);
end

rule "Add to hierarchy as parent"

when
    father: Request( getStatusBRMS()== "SAVED", getJerarquia() == null, parents.parents == null);
then
    System.out.println("Creando Jerarquia...");
    System.out.println("Parent: "+father.getDevice().getSysId());
    Jerarquia jerarquia= new Jerarquia();
    jerarquia.getNodos().add(father);
    jerarquia.setId(father.getDevice().getSysId());
    jerarquia.setType("GAMESA");
    father.setJerarquia(jerarquia);
    insert(jerarquia);
    update(father);
end


rule "SAI gamesa"
   no-loop true
when
     request1 : Request(device.name == "SAI_", statusBRMS == "INICIAL", event.name == "NODE DOWN", $sysID:device.sysId)
     request2 : Request($sysID != null,statusBRMS == "RESGISTRED",event.name== "POWER FAIL",device.sysId == $sysID);
then
    System.out.println("SAI down con previo power fail:");
    request2.setStatusBRMS("RESGISTRED");
    System.out.println("return to FUSE: WAIT for childrens");
    request1.getEvent().setName("POWER FAIL + NODE DOWN");
    request1.setStatusBRMS("WAIT");
    
    
end




rule "busca papa"
 no-loop true
when 
    request : Request(getStatusBRMS() == "WAIT", parents.parents.size > 0, $padres:parents.parents,$idHijo:device.sysId)
    request2 : Request( new Parent(device.sysId ) memberOf  $padres, $idPadre:device.sysId );

then 
System.out.println("device: "+$idHijo+ " Es hijo de "+$idPadre );

end 


rule "busca papa ligth"
 no-loop true
when 
    request : Request(getStatusBRMS() == "RESGISTRED", parents.parents.size > 0, $padres:parents.parents)
then 
System.out.println("ADSdsdasdasdasd version ligth :-D"+$padres );
end

