package com.ikusi.brms.beans;


rule "test envio request"
    no-loop true
when 
    request : Request( getEvent().getName()== "Test_0_3_XXX" )
then
    System.out.println("regla evaluada ver 1.0:"+request.getEvent().getName());
    request.getResponse().setResultado("CREATE");
    request.getResponse().setTiempoEspera(2);

    update( request );
    
end 


rule "device en memoria" 
   no-loop true
when
    request : Request( event.name == "Test_0_3_XXX", statusBRMS=="INICIAL", $sysID:device.sysId)
    Request($sysID != null,inMemory == true, device.sysId == $sysID);
    
then 
    System.out.println("the device: "+request.getDevice().getSysId() +" is already in memory... ");
    System.out.println("whit event: "+request.getEvent().getName());
    System.out.println("return to FUSE: NO");
    retract(request);
end

rule "device no en memoria" 
   no-loop true
when
    request : Request( event.name == "Test_0_3_XXX", inMemory == false)
then
    System.out.println("the device was insert in memory:"+request.getDevice().getSysId());
    request.setInMemory(true);
    request.setStatusBRMS("RESGISTRED");
    update(request);
    
end




